= Ui Setup
:author: mitm
:revnumber: 1.0
:revdate: 5/30/2020
:experimental:

Install is based off the link:https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions[Using Node.js with GitHub Actions] guide using the cloned repository link:https://gitlab.com/antora/antora-ui-default.git[https://gitlab.com/antora/antora-ui-default.git].

. Definitions:
.. Github Web Interface (GWI)
.. Git Command Line Interface (CLI)
.. Continuous Integration (CI)

== Overview

We use the pre-configured `package-lock` and `package-lock.json` files included in the import of the Antora UI repository therefore we only need to use the `npm ci` command to generate the project build. We use a secondary workflow to publish our ui releases which will be triggerd whenver a tag is pushed to the repository. If the publish succedes, we then notify the jMonkeyEngine Wiki that a new release is available, which will trigger its workflow. That workflow will always pull from the latest release and re-build the wiki.

== Import Repository

. From a GitHub account repository tab, select the btn:[New] button.
. On the "`Create a new repository`" page, select the 'Import a repository' link.
. Enter the repository link `+++https://gitlab.com/antora/antora-ui-default.git+++`.
. Enter a name of `jme-ui`.
. Click the btn:[Begin Import] button when ready.

== Workflow Setup

GitHub Actions requires a workflow file located in a `.github/workflows` folder. Ours is named main.yml.

[NOTE]
====
You can edit/add the main.yml from a git (CLI) or the (GWI) only.

This tutorial uses (CLI) for workflow file edits, and the Atom Editor for editing all other files. Since both the (CLI) and Atom Editor are working with the same repository, both will stay synchronized with the the local repository.
====

. From the (CLI), clone the new repository.
.. Create a new folder `.github/workflows`.
.. Add the "`main.yml`" file as a new workflow.
+
--
.main.yml
```
# This file can be used to configure the Node.js build for Antora ui without
# having Node installed locally. See 'setup-docs/setup.adoc' in the root of this
# repo for details of how to use this file.
#
# The action add-and-commit will commit package-lock.json and package.json if
# changes are made to the files.
#
# If the package-lock.json or package.json files are updated or new depends are
# installed, the 'npm ci' should always be ran thereafter to speed up build
# times. When ci is active, the package-lock.json and package.json files in root
# will not be updated.

name: Build UI

on:
  push:
    branches: [ master ]

  pull_request:

jobs:
  build:

    #Static version is used to maintain stability
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        #Static version is used to maintain stability
        node-version: [12.17.0]

    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run with CI
      run: npm ci

#    - name: Audit Depends
#      run: npm audit

    # Build the ui.
    - name: Build Bundle
      id: build_bundle
      run: gulp bundle

    # Detects any updates to package-lock.json and package.json and commits the
    # files to root.
    # see:
    # https://github.com/marketplace/actions/add-commit?version=v4.1.0
    # for use options.
    - name: Commit Packages
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit files for CI workflow"
        # Commits these files to root if and only if there are changes.
        add: "package-lock.json package.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The main points of interest are as follows.

```
#Static version is used to maintain stability
runs-on: ubuntu-18.04

#Static version is used to maintain stability
node-version: [12.7.0]
```

With the above lines, we are using a static version of Node and Ubuntu so that we maintain control of when the repository is updated. Updates can potentially break things and we would find out after the fact rather than knowing immediately that there was a problem.

```
- name: Commit Packages
  uses: EndBug/add-and-commit@v4
  with:
    message: "Commit files for CI workflow"
    # Commits these files to root if and only if there are changes.
    add: "package-lock.json package.json"
```
This command will commit the files `package-lock.json` and `package.json` when there are changes to the files.

```
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
The `secrets.GITHUB_TOKEN` doesn't have authorization to create any successive events so we avoid an infinate loop of commit, run workflows, commit, run workflows.
--
.. Add, commit and push master to the repository.

== New Releases

We have a sucessful build so now we need to configure our workflow to publish releases to the repository. This workflow will also notify the jme wiki that a release was pushed so it will run it's workflow. That will pull the latest release of the ui into the wiki.

This workflow will run whenever a symantic versioned tag is pushed to the repository.

. Add the "`release.yml`" file as a new workflow.
. Add, commit and push master to the repository.

.release.yml
```
# This workflow will push a release whenver a tag is pushed to the repository.
name: "tagged-release"

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:

    #Static version is used to maintain stability
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        #Static version is used to maintain stability
        node-version: [12.17.0]

    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Do not use this workflow with the install command. A stable environment is
    # already expected for releases.
    - name: Run with CI
      run: npm ci

    # Build to ui for release.
    - name: Build Bundle
      id: build_bundle
      run: gulp bundle

    # Strip the refs/heads/ from GITHUB_REF leaving only the tag name.
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    # Deploy a new release.
    # see: https://github.com/marvinpinto/action-automatic-releases
    - name: Upload Release
      if: ( steps.build_bundle.outcome  != 'failure' )
        &&  ( steps.build_bundle.outcome != 'skipped' )
      id: upload_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: format('jme-ui {0}', ${{ steps.vars.outputs.tag }})
          files: ./build/ui-bundle.zip

    # Notify the docs repo we have a new ui.
    - name: Docs Dispatch Event
      if: ( steps.upload_release.outcome  != 'failure' )
        &&  ( steps.upload_release.outcome != 'skipped' )
      run: |
       curl -X POST https://api.github.com/repos/mitm001/docs.jmonkeyengine.org/dispatches \
       --user ${{ secrets.JME_UI_DISPATCH }} \
       --data '{"event_type":"ui-build","client_payload":{"sha": "${{ github.sha }}"}}'
    ```
