---
# GitHub workflow for commits pushed to the antori-ui-bundle repo

# This workflow will commit "package-lock.json" and "package.json" if
# changes occur to those files.
# Committing such changes speeds up future builds.

name: CI at GitHub
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    # Specify environment (to maintain stability).
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Specify Node.js version (to maintain stability).
        node-version: [18.12.0]
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Do not use the install command (to maintain stability).
      - name: Run with CI
        run: npm ci

      # - name: Scan for Vulnerabilities
      #   run: npm audit

      # Build the Antora UI bundle for release.
      - name: Build bundle
        id: build_bundle
        run: gulp bundle

      # Detects any updates to package-lock.json and package.json
      # and commits the files.
      # See https://github.com/marketplace/actions/add-commit
      # for use options.
      - name: Commit packages
        uses: EndBug/add-and-commit@v9
        with:
          message: "Commit files for CI workflow"
          # Commits these files if and only if there are changes.
          add: "package-lock.json package.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
