# This workflow will deploy a new release
# whenver a tag beginning with "v" is pushed to the repository.
name: "tagged-release"

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:

    # Specify environment (to maintain stability).
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        # Specify Node.js version (to maintain stability).
        node-version: [12.18.0]

    steps:
    - name: Clone the repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Do not use the install command (to maintain stability).
    - name: Run with CI
      run: npm ci

    # Build the Antora UI bundle for release.
    - name: Build Bundle
      id: build_bundle
      run: gulp bundle

    # Strip the refs/heads/ from GITHUB_REF leaving only the tag name.
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    # Deploy a new release.
    # see: https://github.com/marvinpinto/action-automatic-releases for param
    # options.
    - name: Upload Release
      if: ( steps.build_bundle.outcome  != 'failure' )
        &&  ( steps.build_bundle.outcome != 'skipped' )
      id: upload_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./build/ui-bundle.zip
